fos_ck_editor:
    base_path: "build/ckeditor"
    js_path:   "build/ckeditor/ckeditor.js"
    configs:
        my_config:
            toolbar: basic
    toolbars:
        configs:
            editor:
                -
                    - Underline
                    - Bold
                    - Italic
                    - Strike
                    - RemoveFormat
                    - NumberedList
                    - BulletedList
                    - Outdent
                    - Indent
                    - Blockquote
                    - CreateDiv
                    - JustifyLeft
                    - JustifyCenter
                    - JustifyRight
                    - JustifyBlock
                    - Link
                    - Unlink
                    - Image
                    - Table
                    - HorizontalRule
                - /
                -
                    - Styles
                    - Format
                    - Font
                    - FontSize
                    - TextColor
                    - BGColor
