# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets: # Contient la liste des filtres
        sizeOne: # Nom du filtre
            quality: 95 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                upscale:
                    min: [ 500,500 ]
                thumbnail:
                    size: [ 500,500 ]
                    mode: outbound
        home_activity: # Nom du filtre
            quality: 95 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                upscale:
                    min: [ 400,300 ]
                thumbnail:
                    size: [ 400,300 ]
                    mode: outbound
        actuality: # Nom du filtre
            quality: 100 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                upscale:
                    min: [ 320,220 ]
                thumbnail:
                    size: [ 320,220 ]
                    mode: outbound
        img_ressource:
            quality: 95
            filters:
                thumbnail:
                    size: [ 100,100 ]
                    mode: outbound
        carre_200:
            quality: 95
            filters:
                upscale:
                    min: [ 200,200 ]
                thumbnail:
                    size: [200,200]
                    mode: outbound
