
vich_uploader:
  db_driver: orm
  mappings:
    coach_image:
      uri_prefix: /uploads
      upload_destination:  '%upload_directory%'
      namer: Vich\UploaderBundle\Naming\UniqidNamer

    actuality_file:
       uri_prefix: /uploads/actualites
       upload_destination:  '%upload_directory%/actualites'
       namer: Vich\UploaderBundle\Naming\UniqidNamer

    activity_file:
     uri_prefix: /uploads/activites
     upload_destination:  '%upload_directory%/activites'
     namer: Vich\UploaderBundle\Naming\UniqidNamer

    transformation_image:
      uri_prefix: /uploads/transformations
      upload_destination:  '%upload_directory%/transformations'
      namer: Vich\UploaderBundle\Naming\UniqidNamer

    planning_file:
      uri_prefix: /uploads/planning
      upload_destination:  '%upload_directory%/planning'
      namer: Vich\UploaderBundle\Naming\UniqidNamer

    programStep_file:
      uri_prefix: /uploads/programStep
      upload_destination:  '%upload_directory%/programStep'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
